# Generated by Django 6.1.1 on 2026-09-22 01:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('duracion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('creditos', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=9)),
                ('cupo', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('num_alumnos', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('horario', models.CharField(max_length=100)),
                ('aula', models.CharField(blank=True, default='', max_length=20)),
                ('turno', models.CharField(choices=[('MAT', 'Matutino'), ('VES', 'Vespertino'), ('MIX', 'Mixto')], default='MAT', max_length=3)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['periodo', 'materia'],
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('matricula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('semestre', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('especialidad', models.CharField(blank=True, default='', max_length=100)),
                ('estatus', models.CharField(choices=[('ACTIVO', 'Activo'), ('BAJA_TEMP', 'Baja temporal'), ('BAJA_DEF', 'Baja definitiva'), ('EGRESADO', 'Egresado'), ('TITULADO', 'Titulado')], default='ACTIVO', max_length=10)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='academico.carrera')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['matricula'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))])),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('fecha_captura', models.DateField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='academico.alumno')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='academico.grupo')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['alumno', 'grupo'],
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='grupos',
            field=models.ManyToManyField(blank=True, related_name='alumnos', through='academico.Calificacion', to='academico.grupo'),
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('unidades', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('creditos', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materias', to='academico.carrera')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='academico.materia'),
        ),
        migrations.AddConstraint(
            model_name='calificacion',
            constraint=models.UniqueConstraint(fields=('alumno', 'grupo'), name='unicidad_inscripcion_alumno_grupo'),
        ),
        migrations.AddConstraint(
            model_name='materia',
            constraint=models.UniqueConstraint(fields=('nombre', 'carrera'), name='unicidad_materia_por_carrera'),
        ),
        migrations.AddConstraint(
            model_name='grupo',
            constraint=models.UniqueConstraint(fields=('materia', 'periodo', 'horario', 'aula'), name='unicidad_grupo_por_materia_periodo_horario_aula'),
        ),
    ]
