# Generated by Django 6.1.1 on 2026-10-04 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_asigna_rol_administrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='alumno',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_de_alumno', to='academico.alumno', verbose_name='Alumno asociado'),
        ),
    ]
