# Generated by Django 6.1.1 on 2026-10-05 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_grupo_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='academico.grupo'),
        ),
    ]
